FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

run npm install -g nodemon 

# Copy the rest of the application
COPY . .

# Command to run the app
CMD ["npm", "run", "server"]
